from typing import Optional


def stitch_clips(
    clip_urls: list[str],
    transitions: Optional[list[str]] = None,
    captions_text: Optional[str] = None,
    music_url: Optional[str] = None,
) -> str:
    """Build an FFmpeg command to stitch video clips together with transitions and optional captions/music.

    Returns the FFmpeg command as a string (does not execute it).
    """
    if not clip_urls:
        return ""

    if transitions is None:
        transitions = ["fade"] * (len(clip_urls) - 1)

    parts = []
    filter_complex_parts = []
    inputs = []
    # Build filter complex for concatenation
    # For simplicity, use concat filter with fade transitions between clips
    # Each clip gets a trim + setpts + optional fade

    for i, url in enumerate(clip_urls):
        input_label = f"v{i}"
        inputs.append(f' -i "{url}"')

        if i == 0:
            # First clip - no fade in transition from nothing, just keep it
            filter_complex_parts.append(
                f"[{i}:v:0]setpts=PTS-STARTPTS[{input_label}_v]"
            )
            filter_complex_parts.append(
                f"[{i}:a:0]asetpts=PTS-STARTPTS[{input_label}_a]"
            )
        else:
            # Apply fade in transition
            transition = transitions[i - 1] if (i - 1) < len(transitions) else "fade"
            fade_duration = 0.5

            filter_complex_parts.append(
                f"[{i}:v:0]setpts=PTS-STARTPTS[{input_label}_v]"
            )
            filter_complex_parts.append(
                f"[{i}:a:0]asetpts=PTS-STARTPTS[{input_label}_a]"
            )

    # Build concat input labels
    v_labels = "".join(f"[v{i}_v]" for i in range(len(clip_urls)))
    a_labels = "".join(f"[v{i}_a]" for i in range(len(clip_urls)))

    concat_inputs = f"{v_labels}{a_labels}concat=n={len(clip_urls)}:v=1:a=1[out_v][out_a]"
    filter_complex_parts.append(concat_inputs)

    # If captions file provided, add subtitles filter
    if captions_text:
        filter_complex_parts.append(
            f"[out_v]subtitles={captions_text}[out_v_captioned]"
        )
        out_video = "[out_v_captioned]"
    else:
        out_video = "[out_v]"

    filter_complex = ";".join(filter_complex_parts)

    # Build command
    cmd_parts = ["ffmpeg"]
    cmd_parts.extend(inputs)
    cmd_parts.append(f'-filter_complex "{filter_complex}"')
    cmd_parts.append(f'-map "{out_video}"')
    cmd_parts.append('-map "[out_a]"')
    cmd_parts.append("-c:v libx264")
    cmd_parts.append("-preset medium")
    cmd_parts.append("-crf 23")
    cmd_parts.append("-c:a aac")
    cmd_parts.append("-b:a 128k")
    cmd_parts.append("-pix_fmt yuv420p")

    # Add background music if provided
    if music_url:
        cmd_parts.append(f'-i "{music_url}"')
        cmd_parts.append('-filter_complex "[1:a]volume=0.15[bgm];[out_a]amix=inputs=2:duration=first[final_a]"')
        cmd_parts.append('-map "[final_a]"')

    cmd_parts.append("output.mp4")

    return " ".join(cmd_parts)


def generate_ass_captions(scenes: list[dict]) -> str:
    """Generate ASS (Advanced SubStation Alpha) subtitle content from scene data.

    Each scene dict should have 'text' and optionally 'estimated_duration'.
    Returns the complete ASS file content as a string.
    """
    lines = [
        "[Script Info]",
        "; Generated by UGC Video Creator",
        "ScriptType: v4.00+",
        "PlayResX: 1920",
        "PlayResY: 1080",
        "ScaledBorderAndShadow: yes",
        "",
        "[V4+ Styles]",
        "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding",
        "Style: Default,Arial,48,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,1,2,10,10,40,1",
        "Style: Caption,Arial,36,&H00FFFFFF,&H000000FF,&H80000000,&H00000000,0,0,0,0,100,100,0,0,1,2,1,8,10,10,80,1",
        "",
        "[Events]",
        "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text",
    ]

    current_time = 0.0
    for scene in scenes:
        duration = scene.get("estimated_duration", 8.0)
        text = scene.get("text", "")

        start_h = int(current_time // 3600)
        start_m = int((current_time % 3600) // 60)
        start_s = current_time % 60
        end_time = current_time + duration
        end_h = int(end_time // 3600)
        end_m = int((end_time % 3600) // 60)
        end_s = end_time % 60

        start_str = f"{start_h:01d}:{start_m:02d}:{start_s:05.2f}"
        end_str = f"{end_h:01d}:{end_m:02d}:{end_s:05.2f}"

        # Escape ASS special characters
        safe_text = text.replace("{", "\\{").replace("}", "\\}")
        safe_text = safe_text.replace("\n", "\\N")

        lines.append(
            f"Dialogue: 0,{start_str},{end_str},Caption,,0,0,0,,{safe_text}"
        )
        current_time = end_time

    return "\n".join(lines)